{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImageView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nukeui\/animatedimageview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nukeui\/animatedimageview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.github.kean.nukeui\/objc(cs)UIImageView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.github.kean.nukeui\/objc(pl)NSCoding","doc:\/\/com.github.kean.nukeui\/objc(pl)NSObject","doc:\/\/com.github.kean.nukeui\/objc(pl)CALayerDelegate","doc:\/\/com.github.kean.nukeui\/s7CVarArgP","doc:\/\/com.github.kean.nukeui\/s28CustomDebugStringConvertibleP","doc:\/\/com.github.kean.nukeui\/s23CustomStringConvertibleP","doc:\/\/com.github.kean.nukeui\/SQ","doc:\/\/com.github.kean.nukeui\/SH","doc:\/\/com.github.kean.nukeui\/s8SendableP","doc:\/\/com.github.kean.nukeui\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting","doc:\/\/com.github.kean.nukeui\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.github.kean.nukeui\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.github.kean.nukeui\/objc(pl)UIAppearance","doc:\/\/com.github.kean.nukeui\/objc(pl)UIAppearanceContainer","doc:\/\/com.github.kean.nukeui\/objc(pl)UICoordinateSpace","doc:\/\/com.github.kean.nukeui\/objc(pl)UIDynamicItem","doc:\/\/com.github.kean.nukeui\/objc(pl)UIFocusEnvironment","doc:\/\/com.github.kean.nukeui\/objc(pl)UIFocusItem","doc:\/\/com.github.kean.nukeui\/objc(pl)UIFocusItemContainer","doc:\/\/com.github.kean.nukeui\/objc(pl)UILargeContentViewerItem","doc:\/\/com.github.kean.nukeui\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.github.kean.nukeui\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.github.kean.nukeui\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.github.kean.nukeui\/objc(pl)UITraitEnvironment","doc:\/\/com.github.kean.nukeui\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView\/display(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImageView"}],"title":"AnimatedImageView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@NukeUI@objc(cs)AnimatedImageView","modules":[{"name":"NukeUI"}],"navigatorTitle":[{"kind":"identifier","text":"AnimatedImageView"}]},"hierarchy":{"paths":[["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI"]]},"seeAlsoSections":[{"title":"Other Views","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/Image","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView"],"generated":true}],"references":{"doc://com.github.kean.nukeui/documentation/NukeUI":{"role":"collection","title":"NukeUI","abstract":[{"type":"text","text":"Image loading for SwiftUI, UIKit, and AppKit views."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI","kind":"symbol","type":"topic","url":"\/documentation\/nukeui"},"doc://com.github.kean.nukeui/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.github.kean.nukeui\/SH"},"doc://com.github.kean.nukeui/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIFocusItemContainer"},"doc://com.github.kean.nukeui/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.github.kean.nukeui\/s8SendableP"},"doc://com.github.kean.nukeui/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UILargeContentViewerItem"},"doc://com.github.kean.nukeui/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UITraitEnvironment"},"doc://com.github.kean.nukeui/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIUserActivityRestoring"},"doc://com.github.kean.nukeui/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)NSCoding"},"doc://com.github.kean.nukeui/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIAccessibilityIdentification"},"doc://com.github.kean.nukeui/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.github.kean.nukeui/documentation/NukeUI/AnimatedImageView/initWithImage:":{"role":"symbol","title":"initWithImage:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView\/initWithImage:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithImage:"}],"url":"\/documentation\/nukeui\/animatedimageview\/initwithimage:"},"doc://com.github.kean.nukeui/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.github.kean.nukeui\/s23CustomStringConvertibleP"},"doc://com.github.kean.nukeui/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)NSObject"},"doc://com.github.kean.nukeui/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)CALayerDelegate"},"doc://com.github.kean.nukeui/documentation/NukeUI/Image":{"role":"symbol","title":"Image","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"abstract":[{"type":"text","text":"Displays images. Supports animated images and video playback."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/Image","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Image"}],"url":"\/documentation\/nukeui\/image"},"doc://com.github.kean.nukeui/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.github.kean.nukeui\/s28CustomDebugStringConvertibleP"},"doc://com.github.kean.nukeui/documentation/NukeUI/AnimatedImageView/display(_:)":{"role":"symbol","title":"display(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"display"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CALayer","preciseIdentifier":"c:objc(cs)CALayer"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Layer delegate method called periodically by the layer. "},{"type":"strong","inlineContent":[{"type":"text","text":"Should not"}]},{"type":"text","text":" be called manually."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView\/display(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"displayLayer:"}],"url":"\/documentation\/nukeui\/animatedimageview\/display(_:)"},"doc://com.github.kean.nukeui/documentation/NukeUI/VideoPlayerView":{"role":"symbol","title":"VideoPlayerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayerView"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoPlayerView"}],"url":"\/documentation\/nukeui\/videoplayerview"},"doc://com.github.kean.nukeui/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIFocusEnvironment"},"doc://com.github.kean.nukeui/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIFocusItem"},"doc://com.github.kean.nukeui/documentation/NukeUI/AnimatedImageView/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/nukeui\/animatedimageview\/initwithframe:"},"doc://com.github.kean.nukeui/documentation/NukeUI/AnimatedImageView/initWithImage:highlightedImage:":{"role":"symbol","title":"initWithImage:highlightedImage:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:highlightedImage:"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView\/initWithImage:highlightedImage:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithImage:highlightedImage:"}],"url":"\/documentation\/nukeui\/animatedimageview\/initwithimage:highlightedimage:"},"doc://com.github.kean.nukeui/documentation/NukeUI/AnimatedImageView":{"role":"symbol","title":"AnimatedImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImageView"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnimatedImageView"}],"url":"\/documentation\/nukeui\/animatedimageview"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView":{"role":"symbol","title":"ImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageView"}],"abstract":[{"type":"text","text":"Displays images. Supports animated images and video playback."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageView"}],"url":"\/documentation\/nukeui\/imageview"},"doc://com.github.kean.nukeui/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting":{"type":"unresolvable","title":"UIKit.UIAccessibilityContentSizeCategoryImageAdjusting","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting"},"doc://com.github.kean.nukeui/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.github.kean.nukeui\/SQ"},"doc://com.github.kean.nukeui/objc(cs)UIImageView":{"type":"unresolvable","title":"UIImageView","identifier":"doc:\/\/com.github.kean.nukeui\/objc(cs)UIImageView"},"doc://com.github.kean.nukeui/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIAppearanceContainer"},"doc://com.github.kean.nukeui/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.github.kean.nukeui/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIDynamicItem"},"doc://com.github.kean.nukeui/documentation/NukeUI/AnimatedImageView/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/nukeui\/animatedimageview\/initwithcoder:"},"doc://com.github.kean.nukeui/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.github.kean.nukeui\/s7CVarArgP"},"doc://com.github.kean.nukeui/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIAppearance"},"doc://com.github.kean.nukeui/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.github.kean.nukeui/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UICoordinateSpace"},"doc://com.github.kean.nukeui/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIResponderStandardEditActions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AnimatedImageView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AnimatedImageView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AnimatedImageView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView\/display(_:)","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView\/initWithCoder:","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView\/initWithFrame:","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView\/initWithImage:","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView\/initWithImage:highlightedImage:"]}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Other Views","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImageView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1AnimatedImageView~1display(_:)\/title","value":"displayLayer:"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1AnimatedImageView~1display(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"displayLayer:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1VideoPlayerView\/title","value":"VideoPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1VideoPlayerView\/fragments","value":[{"kind":"identifier","text":"VideoPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1AnimatedImageView\/title","value":"AnimatedImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1AnimatedImageView\/fragments","value":[{"kind":"identifier","text":"AnimatedImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1ImageView\/title","value":"ImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1ImageView\/fragments","value":[{"kind":"identifier","text":"ImageView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}