{"seeAlsoSections":[{"title":"Other Views","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/Image","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageView"}],"title":"ImageView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@NukeUI@objc(cs)ImageView","modules":[{"name":"NukeUI"}],"navigatorTitle":[{"kind":"identifier","text":"ImageView"}]},"abstract":[{"type":"text","text":"Displays images. Supports animated images and video playback."}],"sections":[],"identifier":{"url":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.github.kean.nukeui\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.github.kean.nukeui\/objc(pl)NSCoding","doc:\/\/com.github.kean.nukeui\/objc(pl)NSObject","doc:\/\/com.github.kean.nukeui\/objc(pl)CALayerDelegate","doc:\/\/com.github.kean.nukeui\/s7CVarArgP","doc:\/\/com.github.kean.nukeui\/s28CustomDebugStringConvertibleP","doc:\/\/com.github.kean.nukeui\/s23CustomStringConvertibleP","doc:\/\/com.github.kean.nukeui\/SQ","doc:\/\/com.github.kean.nukeui\/SH","doc:\/\/com.github.kean.nukeui\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.github.kean.nukeui\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.github.kean.nukeui\/objc(pl)UIAppearance","doc:\/\/com.github.kean.nukeui\/objc(pl)UIAppearanceContainer","doc:\/\/com.github.kean.nukeui\/objc(pl)UICoordinateSpace","doc:\/\/com.github.kean.nukeui\/objc(pl)UIDynamicItem","doc:\/\/com.github.kean.nukeui\/objc(pl)UIFocusEnvironment","doc:\/\/com.github.kean.nukeui\/objc(pl)UIFocusItem","doc:\/\/com.github.kean.nukeui\/objc(pl)UIFocusItemContainer","doc:\/\/com.github.kean.nukeui\/objc(pl)UILargeContentViewerItem","doc:\/\/com.github.kean.nukeui\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.github.kean.nukeui\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.github.kean.nukeui\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.github.kean.nukeui\/objc(pl)UITraitEnvironment","doc:\/\/com.github.kean.nukeui\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/init(frame:)","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/init(coder:)"]},{"title":"Displaying Images","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/image","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/imageContainer"]},{"title":"Accessing Underlying Views","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/imageView","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/animatedImageView","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/videoPlayerView"]},{"title":"Registering Custom Views","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/customContentView","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/registerContentView(_:)","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/removeAllRegisteredContentViews()"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/isAnimatedImageRenderingEnabled","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/isVideoLooping","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/isVideoRenderingEnabled","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/resizingMode"]}],"variants":[{"paths":["\/documentation\/nukeui\/imageview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nukeui\/imageview"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageView"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.github.kean.nukeui/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)CALayerDelegate"},"doc://com.github.kean.nukeui/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UITraitEnvironment"},"doc://com.github.kean.nukeui/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIAppearance"},"doc://com.github.kean.nukeui/documentation/NukeUI":{"role":"collection","title":"NukeUI","abstract":[{"type":"text","text":"Image loading for SwiftUI, UIKit, and AppKit views."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI","kind":"symbol","type":"topic","url":"\/documentation\/nukeui"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView/removeAllRegisteredContentViews()":{"role":"symbol","title":"removeAllRegisteredContentViews()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllRegisteredContentViews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/removeAllRegisteredContentViews()","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/imageview\/removeallregisteredcontentviews()"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView/videoPlayerView":{"role":"symbol","title":"videoPlayerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoPlayerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoPlayerView","preciseIdentifier":"c:@M@NukeUI@objc(cs)VideoPlayerView"}],"abstract":[{"type":"text","text":"Returns an underlying video player view."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/videoPlayerView","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/imageview\/videoplayerview"},"doc://com.github.kean.nukeui/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)NSObject"},"doc://com.github.kean.nukeui/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.github.kean.nukeui\/SH"},"doc://com.github.kean.nukeui/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UILargeContentViewerItem"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/nukeui\/imageview\/init(frame:)"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView/image":{"role":"symbol","title":"image","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlatformImage","preciseIdentifier":"s:4Nuke13PlatformImagea"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/image","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/imageview\/image"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView/imageContainer":{"role":"symbol","title":"imageContainer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageContainer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageContainer","preciseIdentifier":"s:6NukeUI14ImageContainera"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Displays the given image."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/imageContainer","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/imageview\/imagecontainer"},"doc://com.github.kean.nukeui/documentation/NukeUI/AnimatedImageView":{"role":"symbol","title":"AnimatedImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImageView"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnimatedImageView"}],"url":"\/documentation\/nukeui\/animatedimageview"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView/imageView":{"role":"symbol","title":"imageView","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"_PlatformImageView","preciseIdentifier":"s:6NukeUI18_PlatformImageViewa"}],"abstract":[{"type":"text","text":"Returns an underlying image view."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/imageView","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/imageview\/imageview"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView/resizingMode":{"role":"symbol","title":"resizingMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"resizingMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageResizingMode","preciseIdentifier":"s:6NukeUI17ImageResizingModeO"}],"abstract":[{"type":"text","text":"Sets the content mode for all container views."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/resizingMode","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/imageview\/resizingmode"},"doc://com.github.kean.nukeui/documentation/NukeUI/Image":{"role":"symbol","title":"Image","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"abstract":[{"type":"text","text":"Displays images. Supports animated images and video playback."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/Image","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Image"}],"url":"\/documentation\/nukeui\/image"},"doc://com.github.kean.nukeui/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.github.kean.nukeui\/objc(cs)UIView"},"doc://com.github.kean.nukeui/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.github.kean.nukeui\/s7CVarArgP"},"doc://com.github.kean.nukeui/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.github.kean.nukeui\/s23CustomStringConvertibleP"},"doc://com.github.kean.nukeui/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIDynamicItem"},"doc://com.github.kean.nukeui/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.github.kean.nukeui/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UICoordinateSpace"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView/animatedImageView":{"role":"symbol","title":"animatedImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimatedImageView","preciseIdentifier":"c:@M@NukeUI@objc(cs)AnimatedImageView"}],"abstract":[{"type":"text","text":"Returns an underlying animated image view used for rendering animated images."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/animatedImageView","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/imageview\/animatedimageview"},"doc://com.github.kean.nukeui/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.github.kean.nukeui\/s28CustomDebugStringConvertibleP"},"doc://com.github.kean.nukeui/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIAppearanceContainer"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView/isAnimatedImageRenderingEnabled":{"role":"symbol","title":"isAnimatedImageRenderingEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAnimatedImageRenderingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"codeVoice","code":"true"},{"type":"text","text":" by default. If disabled, animated image rendering will be disabled."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/isAnimatedImageRenderingEnabled","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/imageview\/isanimatedimagerenderingenabled"},"doc://com.github.kean.nukeui/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIResponderStandardEditActions"},"doc://com.github.kean.nukeui/documentation/NukeUI/VideoPlayerView":{"role":"symbol","title":"VideoPlayerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayerView"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoPlayerView"}],"url":"\/documentation\/nukeui\/videoplayerview"},"doc://com.github.kean.nukeui/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIFocusItemContainer"},"doc://com.github.kean.nukeui/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)NSCoding"},"doc://com.github.kean.nukeui/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIUserActivityRestoring"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView/registerContentView(_:)":{"role":"symbol","title":"registerContentView(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerContentView"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"ImageContainer","preciseIdentifier":"s:6NukeUI14ImageContainera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"_PlatformBaseView","preciseIdentifier":"s:6NukeUI17_PlatformBaseViewa"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Registers a custom content view to be used for displaying the given image."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/registerContentView(_:)","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/imageview\/registercontentview(_:)"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView/isVideoRenderingEnabled":{"role":"symbol","title":"isVideoRenderingEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isVideoRenderingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"codeVoice","code":"true"},{"type":"text","text":" by default. Set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" to enable video support."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/isVideoRenderingEnabled","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/imageview\/isvideorenderingenabled"},"doc://com.github.kean.nukeui/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIFocusEnvironment"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView/customContentView":{"role":"symbol","title":"customContentView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customContentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"_PlatformBaseView","preciseIdentifier":"s:6NukeUI17_PlatformBaseViewa"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/customContentView","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/imageview\/customcontentview"},"doc://com.github.kean.nukeui/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/nukeui\/imageview\/init(coder:)"},"doc://com.github.kean.nukeui/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIAccessibilityIdentification"},"doc://com.github.kean.nukeui/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIFocusItem"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView/isVideoLooping":{"role":"symbol","title":"isVideoLooping","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isVideoLooping"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/isVideoLooping","kind":"symbol","type":"topic","deprecated":true,"url":"\/documentation\/nukeui\/imageview\/isvideolooping"},"doc://com.github.kean.nukeui/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView":{"role":"symbol","title":"ImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageView"}],"abstract":[{"type":"text","text":"Displays images. Supports animated images and video playback."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageView"}],"url":"\/documentation\/nukeui\/imageview"},"doc://com.github.kean.nukeui/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.github.kean.nukeui\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ImageView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ImageView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ImageView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Initializers","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/init(frame:)","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/init(coder:)"]}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Other Views","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1ImageView~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1ImageView~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1AnimatedImageView\/title","value":"AnimatedImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1AnimatedImageView\/fragments","value":[{"kind":"identifier","text":"AnimatedImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1VideoPlayerView\/title","value":"VideoPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1VideoPlayerView\/fragments","value":[{"kind":"identifier","text":"VideoPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1ImageView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1ImageView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1ImageView\/title","value":"ImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1ImageView\/fragments","value":[{"kind":"identifier","text":"ImageView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}