{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayerView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nukeui\/videoplayerview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nukeui\/videoplayerview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.github.kean.nukeui\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.github.kean.nukeui\/objc(pl)NSCoding","doc:\/\/com.github.kean.nukeui\/objc(pl)NSObject","doc:\/\/com.github.kean.nukeui\/objc(pl)CALayerDelegate","doc:\/\/com.github.kean.nukeui\/s7CVarArgP","doc:\/\/com.github.kean.nukeui\/s28CustomDebugStringConvertibleP","doc:\/\/com.github.kean.nukeui\/s23CustomStringConvertibleP","doc:\/\/com.github.kean.nukeui\/SQ","doc:\/\/com.github.kean.nukeui\/SH","doc:\/\/com.github.kean.nukeui\/s8SendableP","doc:\/\/com.github.kean.nukeui\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.github.kean.nukeui\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.github.kean.nukeui\/objc(pl)UIAppearance","doc:\/\/com.github.kean.nukeui\/objc(pl)UIAppearanceContainer","doc:\/\/com.github.kean.nukeui\/objc(pl)UICoordinateSpace","doc:\/\/com.github.kean.nukeui\/objc(pl)UIDynamicItem","doc:\/\/com.github.kean.nukeui\/objc(pl)UIFocusEnvironment","doc:\/\/com.github.kean.nukeui\/objc(pl)UIFocusItem","doc:\/\/com.github.kean.nukeui\/objc(pl)UIFocusItemContainer","doc:\/\/com.github.kean.nukeui\/objc(pl)UILargeContentViewerItem","doc:\/\/com.github.kean.nukeui\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.github.kean.nukeui\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.github.kean.nukeui\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.github.kean.nukeui\/objc(pl)UITraitEnvironment","doc:\/\/com.github.kean.nukeui\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/asset","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/isLooping","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/playerLayer","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/videoGravity"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/play()","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/reset()","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/restart()","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/willMove(toWindow:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/layerClass"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayerView"}],"title":"VideoPlayerView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@NukeUI@objc(cs)VideoPlayerView","modules":[{"name":"NukeUI"}],"navigatorTitle":[{"kind":"identifier","text":"VideoPlayerView"}]},"hierarchy":{"paths":[["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI"]]},"seeAlsoSections":[{"title":"Other Views","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/Image","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView"],"generated":true}],"references":{"doc://com.github.kean.nukeui/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.github.kean.nukeui\/s28CustomDebugStringConvertibleP"},"doc://com.github.kean.nukeui/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIAccessibilityIdentification"},"doc://com.github.kean.nukeui/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIFocusItem"},"doc://com.github.kean.nukeui/documentation/NukeUI":{"role":"collection","title":"NukeUI","abstract":[{"type":"text","text":"Image loading for SwiftUI, UIKit, and AppKit views."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI","kind":"symbol","type":"topic","url":"\/documentation\/nukeui"},"doc://com.github.kean.nukeui/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIFocusItemContainer"},"doc://com.github.kean.nukeui/documentation/NukeUI/VideoPlayerView":{"role":"symbol","title":"VideoPlayerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayerView"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoPlayerView"}],"url":"\/documentation\/nukeui\/videoplayerview"},"doc://com.github.kean.nukeui/documentation/NukeUI/VideoPlayerView/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/nukeui\/videoplayerview\/initwithcoder:"},"doc://com.github.kean.nukeui/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIAppearance"},"doc://com.github.kean.nukeui/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIAppearanceContainer"},"doc://com.github.kean.nukeui/documentation/NukeUI/Image":{"role":"symbol","title":"Image","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"abstract":[{"type":"text","text":"Displays images. Supports animated images and video playback."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/Image","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Image"}],"url":"\/documentation\/nukeui\/image"},"doc://com.github.kean.nukeui/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UILargeContentViewerItem"},"doc://com.github.kean.nukeui/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.github.kean.nukeui\/s23CustomStringConvertibleP"},"doc://com.github.kean.nukeui/documentation/NukeUI/VideoPlayerView/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/nukeui\/videoplayerview\/initwithframe:"},"doc://com.github.kean.nukeui/documentation/NukeUI/VideoPlayerView/restart()":{"role":"symbol","title":"restart()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"restart"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/restart()","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/videoplayerview\/restart()"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView":{"role":"symbol","title":"ImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageView"}],"abstract":[{"type":"text","text":"Displays images. Supports animated images and video playback."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageView"}],"url":"\/documentation\/nukeui\/imageview"},"doc://com.github.kean.nukeui/documentation/NukeUI/VideoPlayerView/willMove(toWindow:)":{"role":"symbol","title":"willMove(toWindow:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willMove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toWindow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/willMove(toWindow:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"willMoveToWindow:"}],"url":"\/documentation\/nukeui\/videoplayerview\/willmove(towindow:)"},"doc://com.github.kean.nukeui/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.github.kean.nukeui\/s7CVarArgP"},"doc://com.github.kean.nukeui/documentation/NukeUI/AnimatedImageView":{"role":"symbol","title":"AnimatedImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImageView"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnimatedImageView"}],"url":"\/documentation\/nukeui\/animatedimageview"},"doc://com.github.kean.nukeui/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.github.kean.nukeui\/SH"},"doc://com.github.kean.nukeui/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIUserActivityRestoring"},"doc://com.github.kean.nukeui/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.github.kean.nukeui\/SQ"},"doc://com.github.kean.nukeui/documentation/NukeUI/VideoPlayerView/layerClass":{"role":"symbol","title":"layerClass","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"layerClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/layerClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layerClass"}],"url":"\/documentation\/nukeui\/videoplayerview\/layerclass"},"doc://com.github.kean.nukeui/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)NSObject"},"doc://com.github.kean.nukeui/documentation/NukeUI/VideoPlayerView/play()":{"role":"symbol","title":"play()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"play"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/play()","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/videoplayerview\/play()"},"doc://com.github.kean.nukeui/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.github.kean.nukeui\/objc(cs)UIView"},"doc://com.github.kean.nukeui/documentation/NukeUI/VideoPlayerView/reset()":{"role":"symbol","title":"reset()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reset"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/reset()","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/videoplayerview\/reset()"},"doc://com.github.kean.nukeui/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UICoordinateSpace"},"doc://com.github.kean.nukeui/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)NSCoding"},"doc://com.github.kean.nukeui/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIDynamicItem"},"doc://com.github.kean.nukeui/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.github.kean.nukeui/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIFocusEnvironment"},"doc://com.github.kean.nukeui/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.github.kean.nukeui/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.github.kean.nukeui\/s8SendableP"},"doc://com.github.kean.nukeui/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.github.kean.nukeui/documentation/NukeUI/VideoPlayerView/asset":{"role":"symbol","title":"asset","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"asset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAsset","preciseIdentifier":"c:objc(cs)AVAsset"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/asset","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/videoplayerview\/asset"},"doc://com.github.kean.nukeui/documentation/NukeUI/VideoPlayerView/isLooping":{"role":"symbol","title":"isLooping","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLooping"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"codeVoice","code":"true"},{"type":"text","text":" by default. If disabled, will only play a video once."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/isLooping","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/videoplayerview\/islooping"},"doc://com.github.kean.nukeui/documentation/NukeUI/VideoPlayerView/videoGravity":{"role":"symbol","title":"videoGravity","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoGravity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVLayerVideoGravity","preciseIdentifier":"c:@T@AVLayerVideoGravity"}],"abstract":[{"type":"codeVoice","code":".resizeAspectFill"},{"type":"text","text":" by default."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/videoGravity","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/videoplayerview\/videogravity"},"doc://com.github.kean.nukeui/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UIResponderStandardEditActions"},"doc://com.github.kean.nukeui/documentation/NukeUI/VideoPlayerView/playerLayer":{"role":"symbol","title":"playerLayer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerLayer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVPlayerLayer","preciseIdentifier":"c:objc(cs)AVPlayerLayer"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/playerLayer","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/videoplayerview\/playerlayer"},"doc://com.github.kean.nukeui/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)CALayerDelegate"},"doc://com.github.kean.nukeui/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.github.kean.nukeui\/objc(pl)UITraitEnvironment"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"VideoPlayerView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"VideoPlayerView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"VideoPlayerView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/layerClass"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/initWithCoder:","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/initWithFrame:","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/willMove(toWindow:)"]}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Other Views","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayerView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1VideoPlayerView\/title","value":"VideoPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1VideoPlayerView\/fragments","value":[{"kind":"identifier","text":"VideoPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1ImageView\/title","value":"ImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1ImageView\/fragments","value":[{"kind":"identifier","text":"ImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1VideoPlayerView~1willMove(toWindow:)\/title","value":"willMoveToWindow:"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1VideoPlayerView~1willMove(toWindow:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willMoveToWindow:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1AnimatedImageView\/title","value":"AnimatedImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1AnimatedImageView\/fragments","value":[{"kind":"identifier","text":"AnimatedImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1VideoPlayerView~1layerClass\/title","value":"layerClass"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1VideoPlayerView~1layerClass\/fragments","value":[{"kind":"identifier","text":"layerClass"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}