{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"There are four main views provided by the framework:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImage"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/Image"},{"type":"text","text":" for SwiftUI"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImageView"},{"type":"text","text":" and "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView"},{"type":"text","text":" for UIKit and AppKit"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImage"},{"type":"text","text":" is designed similar to the native "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/SwiftUI\/AsyncImage"},{"type":"text","text":", but it uses "},{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/kean\/Nuke"},{"type":"text","text":" for loading images so you can take advantage of all of its features, such as caching, prefetching, task coalescing, smart background decompression, request priorities, and more."}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"nukeui-preview"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"NukeUI supports progressive images, has GIF support powered by "},{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/kaishin\/Gifu"},{"type":"text","text":", and can even play short videos, which is "},{"type":"reference","isActive":true,"identifier":"https:\/\/web.dev\/replace-gifs-with-videos\/"},{"type":"text","text":" way to display animated images."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nukeui"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nukeui"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Image loading for SwiftUI, UIKit, and AppKit views."}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"NukeUI","title":"NukeUI","symbolKind":"module","role":"collection","modules":[{"name":"NukeUI"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Essentials","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImage","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImageView","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImageState"]},{"title":"Other Views","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/Image","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView"]},{"title":"Helpers","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/FetchImage","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageResizingMode"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageContainer","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImagePipeline","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageRequest","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageResponse"]}],"references":{"https://developer.apple.com/documentation/SwiftUI/AsyncImage":{"title":"AsyncImage","titleInlineContent":[{"type":"codeVoice","code":"AsyncImage"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/SwiftUI\/AsyncImage","url":"https:\/\/developer.apple.com\/documentation\/SwiftUI\/AsyncImage"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageContainer":{"role":"symbol","title":"ImageContainer","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageContainer"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageContainer"}],"url":"\/documentation\/nukeui\/imagecontainer"},"doc://com.github.kean.nukeui/documentation/NukeUI/FetchImage":{"role":"symbol","title":"FetchImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FetchImage"}],"abstract":[{"type":"text","text":"An observable object that simplifies image loading in SwiftUI."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/FetchImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FetchImage"}],"url":"\/documentation\/nukeui\/fetchimage"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageResizingMode":{"role":"symbol","title":"ImageResizingMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageResizingMode"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageResizingMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageResizingMode"}],"url":"\/documentation\/nukeui\/imageresizingmode"},"https://github.com/kean/Nuke":{"title":"Nuke","titleInlineContent":[{"type":"text","text":"Nuke"}],"type":"link","identifier":"https:\/\/github.com\/kean\/Nuke","url":"https:\/\/github.com\/kean\/Nuke"},"doc://com.github.kean.nukeui/documentation/NukeUI/AnimatedImageView":{"role":"symbol","title":"AnimatedImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImageView"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnimatedImageView"}],"url":"\/documentation\/nukeui\/animatedimageview"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImagePipeline":{"role":"symbol","title":"ImagePipeline","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePipeline"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImagePipeline","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImagePipeline"}],"url":"\/documentation\/nukeui\/imagepipeline"},"doc://com.github.kean.nukeui/documentation/NukeUI/LazyImageView":{"role":"symbol","title":"LazyImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LazyImageView"}],"abstract":[{"type":"text","text":"Lazily loads and displays images."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LazyImageView"}],"url":"\/documentation\/nukeui\/lazyimageview"},"doc://com.github.kean.nukeui/documentation/NukeUI/Image":{"role":"symbol","title":"Image","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"abstract":[{"type":"text","text":"Displays images. Supports animated images and video playback."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/Image","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Image"}],"url":"\/documentation\/nukeui\/image"},"doc://com.github.kean.nukeui/documentation/NukeUI/GIFImageView":{"role":"symbol","title":"GIFImageView","fragments":[{"kind":"identifier","text":"GIFImageView"}],"abstract":[{"type":"text","text":"Example class that conforms to "},{"type":"text","text":"GIFAnimatable"},{"type":"text","text":". Uses default values for the animator frame buffer count and resize behavior. You can either use it directly in your code or use it as a blueprint for your own subclass."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/GIFImageView","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/gifimageview"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageRequest":{"role":"symbol","title":"ImageRequest","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageRequest"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageRequest"}],"url":"\/documentation\/nukeui\/imagerequest"},"nukeui-preview":{"alt":"nukeui demo","type":"image","identifier":"nukeui-preview","variants":[{"url":"\/images\/nukeui-preview.png","traits":["1x","light"]}]},"https://github.com/kaishin/Gifu":{"title":"Gifu","titleInlineContent":[{"type":"text","text":"Gifu"}],"type":"link","identifier":"https:\/\/github.com\/kaishin\/Gifu","url":"https:\/\/github.com\/kaishin\/Gifu"},"https://web.dev/replace-gifs-with-videos/":{"title":"a more efficient","titleInlineContent":[{"type":"text","text":"a more efficient"}],"type":"link","identifier":"https:\/\/web.dev\/replace-gifs-with-videos\/","url":"https:\/\/web.dev\/replace-gifs-with-videos\/"},"doc://com.github.kean.nukeui/documentation/NukeUI/LazyImage":{"role":"symbol","title":"LazyImage","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LazyImage"}],"abstract":[{"type":"text","text":"Lazily loads and displays images."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LazyImage"}],"url":"\/documentation\/nukeui\/lazyimage"},"doc://com.github.kean.nukeui/documentation/NukeUI/LazyImageState":{"role":"symbol","title":"LazyImageState","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LazyImageState"}],"abstract":[{"type":"text","text":"Describes current image state."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImageState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LazyImageState"}],"url":"\/documentation\/nukeui\/lazyimagestate"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageResponse":{"role":"symbol","title":"ImageResponse","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageResponse"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageResponse"}],"url":"\/documentation\/nukeui\/imageresponse"},"doc://com.github.kean.nukeui/documentation/NukeUI/VideoPlayerView":{"role":"symbol","title":"VideoPlayerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayerView"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoPlayerView"}],"url":"\/documentation\/nukeui\/videoplayerview"},"doc://com.github.kean.nukeui/documentation/NukeUI":{"role":"collection","title":"NukeUI","abstract":[{"type":"text","text":"Image loading for SwiftUI, UIKit, and AppKit views."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI","kind":"symbol","type":"topic","url":"\/documentation\/nukeui"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView":{"role":"symbol","title":"ImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageView"}],"abstract":[{"type":"text","text":"Displays images. Supports animated images and video playback."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageView"}],"url":"\/documentation\/nukeui\/imageview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Essentials","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImageView"]},{"title":"Other Views","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView"]},{"title":"Classes","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/GIFImageView"]}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1AnimatedImageView\/title","value":"AnimatedImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1AnimatedImageView\/fragments","value":[{"kind":"identifier","text":"AnimatedImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1LazyImageView\/title","value":"LazyImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1LazyImageView\/fragments","value":[{"kind":"identifier","text":"LazyImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1VideoPlayerView\/title","value":"VideoPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1VideoPlayerView\/fragments","value":[{"kind":"identifier","text":"VideoPlayerView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1ImageView\/title","value":"ImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1ImageView\/fragments","value":[{"kind":"identifier","text":"ImageView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}