{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"display"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"layer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CALayer","preciseIdentifier":"c:objc(cs)CALayer"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"layer","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The delegated layer."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nukeui\/animatedimageview\/display(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nukeui\/animatedimageview\/display(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView\/display(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Layer delegate method called periodically by the layer. "},{"type":"strong","inlineContent":[{"type":"text","text":"Should not"}]},{"type":"text","text":" be called manually."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"display"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CALayer","preciseIdentifier":"c:objc(cs)CALayer"},{"kind":"text","text":")"}],"title":"display(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@NukeUI@objc(cs)AnimatedImageView(im)displayLayer:","modules":[{"name":"NukeUI"}],"navigatorTitle":[{"kind":"identifier","text":"displayLayer:"}]},"hierarchy":{"paths":[["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView"]]},"references":{"doc://com.github.kean.nukeui/documentation/NukeUI":{"role":"collection","title":"NukeUI","abstract":[{"type":"text","text":"Image loading for SwiftUI, UIKit, and AppKit views."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI","kind":"symbol","type":"topic","url":"\/documentation\/nukeui"},"doc://com.github.kean.nukeui/documentation/NukeUI/AnimatedImageView":{"role":"symbol","title":"AnimatedImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImageView"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnimatedImageView"}],"url":"\/documentation\/nukeui\/animatedimageview"},"doc://com.github.kean.nukeui/documentation/NukeUI/AnimatedImageView/display(_:)":{"role":"symbol","title":"display(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"display"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CALayer","preciseIdentifier":"c:objc(cs)CALayer"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Layer delegate method called periodically by the layer. "},{"type":"strong","inlineContent":[{"type":"text","text":"Should not"}]},{"type":"text","text":" be called manually."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/AnimatedImageView\/display(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"displayLayer:"}],"url":"\/documentation\/nukeui\/animatedimageview\/display(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"displayLayer:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"displayLayer:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"displayLayer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CALayer","preciseIdentifier":"c:objc(cs)CALayer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"layer"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1AnimatedImageView\/title","value":"AnimatedImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1AnimatedImageView\/fragments","value":[{"kind":"identifier","text":"AnimatedImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1AnimatedImageView~1display(_:)\/title","value":"displayLayer:"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1AnimatedImageView~1display(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"displayLayer:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}