{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView","preciseIdentifier":"c:@M@NukeUI@objc(cs)ImageView","text":"ImageView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nukeui\/lazyimageview\/imageview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImageView\/imageView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns the underlying image view."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageView","preciseIdentifier":"c:@M@NukeUI@objc(cs)ImageView"}],"title":"imageView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:6NukeUI13LazyImageViewC05imageE0AA0dE0Cvp","modules":[{"name":"NukeUI"}]},"hierarchy":{"paths":[["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImageView"]]},"references":{"doc://com.github.kean.nukeui/documentation/NukeUI/LazyImageView/imageView":{"role":"symbol","title":"imageView","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageView","preciseIdentifier":"c:@M@NukeUI@objc(cs)ImageView"}],"abstract":[{"type":"text","text":"Returns the underlying image view."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImageView\/imageView","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/lazyimageview\/imageview"},"doc://com.github.kean.nukeui/documentation/NukeUI/LazyImageView":{"role":"symbol","title":"LazyImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LazyImageView"}],"abstract":[{"type":"text","text":"Lazily loads and displays images."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LazyImageView"}],"url":"\/documentation\/nukeui\/lazyimageview"},"doc://com.github.kean.nukeui/documentation/NukeUI":{"role":"collection","title":"NukeUI","abstract":[{"type":"text","text":"Image loading for SwiftUI, UIKit, and AppKit views."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI","kind":"symbol","type":"topic","url":"\/documentation\/nukeui"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView":{"role":"symbol","title":"ImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageView"}],"abstract":[{"type":"text","text":"Displays images. Supports animated images and video playback."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageView"}],"url":"\/documentation\/nukeui\/imageview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1LazyImageView\/title","value":"LazyImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1LazyImageView\/fragments","value":[{"kind":"identifier","text":"LazyImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1ImageView\/title","value":"ImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1ImageView\/fragments","value":[{"kind":"identifier","text":"ImageView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}