{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nukeui\/lazyimageview\/init(frame:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nukeui\/lazyimageview\/init(frame:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImageView\/init(frame:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"title":"init(frame:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@NukeUI@objc(cs)LazyImageView(im)initWithFrame:","modules":[{"name":"NukeUI"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}]},"hierarchy":{"paths":[["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImageView"]]},"seeAlsoSections":[{"title":"Initializers","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImageView\/init(coder:)"],"generated":true}],"references":{"doc://com.github.kean.nukeui/documentation/NukeUI/LazyImageView":{"role":"symbol","title":"LazyImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LazyImageView"}],"abstract":[{"type":"text","text":"Lazily loads and displays images."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LazyImageView"}],"url":"\/documentation\/nukeui\/lazyimageview"},"doc://com.github.kean.nukeui/documentation/NukeUI/LazyImageView/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImageView\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/nukeui\/lazyimageview\/init(frame:)"},"doc://com.github.kean.nukeui/documentation/NukeUI/LazyImageView/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImageView\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/nukeui\/lazyimageview\/init(coder:)"},"doc://com.github.kean.nukeui/documentation/NukeUI":{"role":"collection","title":"NukeUI","abstract":[{"type":"text","text":"Image loading for SwiftUI, UIKit, and AppKit views."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI","kind":"symbol","type":"topic","url":"\/documentation\/nukeui"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithFrame:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Initializers","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/LazyImageView\/init(coder:)"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFrame:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"},{"kind":"internalParam","text":"frame"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1LazyImageView\/title","value":"LazyImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1LazyImageView\/fragments","value":[{"kind":"identifier","text":"LazyImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1LazyImageView~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1LazyImageView~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1LazyImageView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1LazyImageView~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}