{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateConstraints"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nukeui\/lazyimageview\/updateconstraints()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nukeui\/lazyimageview\/updateconstraints()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.github.kean.NukeUI\/documentation\/NukeUI\/LazyImageView\/updateConstraints()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateConstraints"},{"kind":"text","text":"()"}],"title":"updateConstraints()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@NukeUI@objc(cs)LazyImageView(im)updateConstraints","modules":[{"name":"NukeUI"}],"navigatorTitle":[{"kind":"identifier","text":"updateConstraints"}]},"hierarchy":{"paths":[["doc:\/\/com.github.kean.NukeUI\/documentation\/NukeUI","doc:\/\/com.github.kean.NukeUI\/documentation\/NukeUI\/LazyImageView"]]},"references":{"doc://com.github.kean.NukeUI/documentation/NukeUI/LazyImageView/updateConstraints()":{"role":"symbol","title":"updateConstraints()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateConstraints"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.NukeUI\/documentation\/NukeUI\/LazyImageView\/updateConstraints()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateConstraints"}],"url":"\/documentation\/nukeui\/lazyimageview\/updateconstraints()"},"doc://com.github.kean.NukeUI/documentation/NukeUI":{"role":"collection","title":"NukeUI","abstract":[{"type":"text","text":"Image loading for SwiftUI, UIKit, and AppKit views."}],"identifier":"doc:\/\/com.github.kean.NukeUI\/documentation\/NukeUI","kind":"symbol","type":"topic","url":"\/documentation\/nukeui"},"doc://com.github.kean.NukeUI/documentation/NukeUI/LazyImageView":{"role":"symbol","title":"LazyImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LazyImageView"}],"abstract":[{"type":"text","text":"Lazily loads and displays images."}],"identifier":"doc:\/\/com.github.kean.NukeUI\/documentation\/NukeUI\/LazyImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LazyImageView"}],"url":"\/documentation\/nukeui\/lazyimageview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateConstraints"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateConstraints"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateConstraints"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.NukeUI~1documentation~1NukeUI~1LazyImageView~1updateConstraints()\/title","value":"updateConstraints"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.NukeUI~1documentation~1NukeUI~1LazyImageView~1updateConstraints()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateConstraints"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.NukeUI~1documentation~1NukeUI~1LazyImageView\/title","value":"LazyImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.NukeUI~1documentation~1NukeUI~1LazyImageView\/fragments","value":[{"kind":"identifier","text":"LazyImageView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}