{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In this guide, you’ll learn about these extensions and all of the available options."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nukeextensions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nukeextensions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.github.kean.nuke-extensions\/documentation\/NukeExtensions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Nuke provides convenience extension for image views with multiple display options."}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"NukeExtensions","title":"NukeExtensions","symbolKind":"module","role":"collection","modules":[{"name":"NukeExtensions"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Articles","identifiers":["doc:\/\/com.github.kean.nuke-extensions\/documentation\/NukeExtensions\/ImageViewExtensions"],"generated":true},{"title":"Protocols","identifiers":["doc:\/\/com.github.kean.nuke-extensions\/documentation\/NukeExtensions\/Nuke_ImageDisplaying"]},{"title":"Structures","identifiers":["doc:\/\/com.github.kean.nuke-extensions\/documentation\/NukeExtensions\/ImageLoadingOptions"]},{"title":"Functions","identifiers":["doc:\/\/com.github.kean.nuke-extensions\/documentation\/NukeExtensions\/cancelRequest(for:)","doc:\/\/com.github.kean.nuke-extensions\/documentation\/NukeExtensions\/loadImage(with:options:into:completion:)","doc:\/\/com.github.kean.nuke-extensions\/documentation\/NukeExtensions\/loadImage(with:options:into:progress:completion:)"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.github.kean.nuke-extensions\/documentation\/NukeExtensions\/ImageDisplayingView"]}],"references":{"doc://com.github.kean.nuke-extensions/documentation/NukeExtensions/Nuke_ImageDisplaying":{"role":"symbol","title":"Nuke_ImageDisplaying","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Nuke_ImageDisplaying"}],"abstract":[{"type":"text","text":"Displays images. Add the conformance to this protocol to your views to make"},{"type":"text","text":" "},{"type":"text","text":"them compatible with Nuke image loading extensions."}],"identifier":"doc:\/\/com.github.kean.nuke-extensions\/documentation\/NukeExtensions\/Nuke_ImageDisplaying","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Nuke_ImageDisplaying"}],"url":"\/documentation\/nukeextensions\/nuke_imagedisplaying"},"doc://com.github.kean.nuke-extensions/documentation/NukeExtensions/loadImage(with:options:into:progress:completion:)":{"role":"symbol","title":"loadImage(with:options:into:progress:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"ImageRequestConvertible","preciseIdentifier":"s:4Nuke23ImageRequestConvertibleP"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageLoadingOptions","preciseIdentifier":"s:14NukeExtensions19ImageLoadingOptionsV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageDisplayingView","preciseIdentifier":"s:14NukeExtensions19ImageDisplayingViewa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageResponse","preciseIdentifier":"s:4Nuke13ImageResponseV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"total"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ImageResponse","preciseIdentifier":"s:4Nuke13ImageResponseV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ImagePipeline","preciseIdentifier":"s:4Nuke13ImagePipelineC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:4Nuke13ImagePipelineC5ErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"ImageTask","preciseIdentifier":"s:4Nuke9ImageTaskC"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Loads an image with the given request and displays it in the view."}],"identifier":"doc:\/\/com.github.kean.nuke-extensions\/documentation\/NukeExtensions\/loadImage(with:options:into:progress:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/nukeextensions\/loadimage(with:options:into:progress:completion:)"},"doc://com.github.kean.nuke-extensions/documentation/NukeExtensions/ImageDisplayingView":{"role":"symbol","title":"ImageDisplayingView","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageDisplayingView"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":" that implements "},{"type":"codeVoice","code":"ImageDisplaying"},{"type":"text","text":" protocol."}],"identifier":"doc:\/\/com.github.kean.nuke-extensions\/documentation\/NukeExtensions\/ImageDisplayingView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageDisplayingView"}],"url":"\/documentation\/nukeextensions\/imagedisplayingview"},"doc://com.github.kean.nuke-extensions/documentation/NukeExtensions/ImageViewExtensions":{"role":"article","title":"Image View Extensions","abstract":[{"type":"text","text":"Learn about extensions for image views."}],"identifier":"doc:\/\/com.github.kean.nuke-extensions\/documentation\/NukeExtensions\/ImageViewExtensions","kind":"article","type":"topic","url":"\/documentation\/nukeextensions\/imageviewextensions"},"doc://com.github.kean.nuke-extensions/documentation/NukeExtensions":{"role":"collection","title":"NukeExtensions","abstract":[{"type":"text","text":"Nuke provides convenience extension for image views with multiple display options."}],"identifier":"doc:\/\/com.github.kean.nuke-extensions\/documentation\/NukeExtensions","kind":"symbol","type":"topic","url":"\/documentation\/nukeextensions"},"doc://com.github.kean.nuke-extensions/documentation/NukeExtensions/loadImage(with:options:into:completion:)":{"role":"symbol","title":"loadImage(with:options:into:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"ImageRequestConvertible","preciseIdentifier":"s:4Nuke23ImageRequestConvertibleP"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageLoadingOptions","preciseIdentifier":"s:14NukeExtensions19ImageLoadingOptionsV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageDisplayingView","preciseIdentifier":"s:14NukeExtensions19ImageDisplayingViewa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ImageResponse","preciseIdentifier":"s:4Nuke13ImageResponseV"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ImagePipeline","preciseIdentifier":"s:4Nuke13ImagePipelineC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:4Nuke13ImagePipelineC5ErrorO"},{"kind":"text","text":">) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ImageTask","preciseIdentifier":"s:4Nuke9ImageTaskC"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Loads an image with the given request and displays it in the view."}],"identifier":"doc:\/\/com.github.kean.nuke-extensions\/documentation\/NukeExtensions\/loadImage(with:options:into:completion:)","kind":"symbol","type":"topic","url":"\/documentation\/nukeextensions\/loadimage(with:options:into:completion:)"},"doc://com.github.kean.nuke-extensions/documentation/NukeExtensions/ImageLoadingOptions":{"role":"symbol","title":"ImageLoadingOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageLoadingOptions"}],"abstract":[{"type":"text","text":"A set of options that control how the image is loaded and displayed."}],"identifier":"doc:\/\/com.github.kean.nuke-extensions\/documentation\/NukeExtensions\/ImageLoadingOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageLoadingOptions"}],"url":"\/documentation\/nukeextensions\/imageloadingoptions"},"doc://com.github.kean.nuke-extensions/documentation/NukeExtensions/cancelRequest(for:)":{"role":"symbol","title":"cancelRequest(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelRequest"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageDisplayingView","preciseIdentifier":"s:14NukeExtensions19ImageDisplayingViewa"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Cancels an outstanding request associated with the view."}],"identifier":"doc:\/\/com.github.kean.nuke-extensions\/documentation\/NukeExtensions\/cancelRequest(for:)","kind":"symbol","type":"topic","url":"\/documentation\/nukeextensions\/cancelrequest(for:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.github.kean.nuke-extensions\/documentation\/NukeExtensions\/ImageViewExtensions"],"generated":true},{"title":"Protocols","identifiers":["doc:\/\/com.github.kean.nuke-extensions\/documentation\/NukeExtensions\/Nuke_ImageDisplaying"]}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nuke-extensions~1documentation~1NukeExtensions~1Nuke_ImageDisplaying\/title","value":"Nuke_ImageDisplaying"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nuke-extensions~1documentation~1NukeExtensions~1Nuke_ImageDisplaying\/fragments","value":[{"kind":"identifier","text":"Nuke_ImageDisplaying"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}