{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoPlayerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView","preciseIdentifier":"c:@M@NukeUI@objc(cs)VideoPlayerView","text":"VideoPlayerView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nukeui\/imageview\/videoplayerview"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/videoPlayerView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns an underlying video player view."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoPlayerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoPlayerView","preciseIdentifier":"c:@M@NukeUI@objc(cs)VideoPlayerView"}],"title":"videoPlayerView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:6NukeUI9ImageViewC011videoPlayerD0AA05VideofD0Cvp","modules":[{"name":"NukeUI"}]},"hierarchy":{"paths":[["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView"]]},"seeAlsoSections":[{"title":"Accessing Underlying Views","identifiers":["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/imageView","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/animatedImageView"],"generated":true}],"references":{"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView":{"role":"symbol","title":"ImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageView"}],"abstract":[{"type":"text","text":"Displays images. Supports animated images and video playback."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageView"}],"url":"\/documentation\/nukeui\/imageview"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView/videoPlayerView":{"role":"symbol","title":"videoPlayerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoPlayerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoPlayerView","preciseIdentifier":"c:@M@NukeUI@objc(cs)VideoPlayerView"}],"abstract":[{"type":"text","text":"Returns an underlying video player view."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/videoPlayerView","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/imageview\/videoplayerview"},"doc://com.github.kean.nukeui/documentation/NukeUI":{"role":"collection","title":"NukeUI","abstract":[{"type":"text","text":"Image loading for SwiftUI, UIKit, and AppKit views."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI","kind":"symbol","type":"topic","url":"\/documentation\/nukeui"},"doc://com.github.kean.nukeui/documentation/NukeUI/VideoPlayerView":{"role":"symbol","title":"VideoPlayerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayerView"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoPlayerView"}],"url":"\/documentation\/nukeui\/videoplayerview"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView/animatedImageView":{"role":"symbol","title":"animatedImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimatedImageView","preciseIdentifier":"c:@M@NukeUI@objc(cs)AnimatedImageView"}],"abstract":[{"type":"text","text":"Returns an underlying animated image view used for rendering animated images."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/animatedImageView","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/imageview\/animatedimageview"},"doc://com.github.kean.nukeui/documentation/NukeUI/ImageView/imageView":{"role":"symbol","title":"imageView","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"_PlatformImageView","preciseIdentifier":"s:6NukeUI18_PlatformImageViewa"}],"abstract":[{"type":"text","text":"Returns an underlying image view."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/ImageView\/imageView","kind":"symbol","type":"topic","url":"\/documentation\/nukeui\/imageview\/imageview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1ImageView\/title","value":"ImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1ImageView\/fragments","value":[{"kind":"identifier","text":"ImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1VideoPlayerView\/title","value":"VideoPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1VideoPlayerView\/fragments","value":[{"kind":"identifier","text":"VideoPlayerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}