{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willMove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toWindow"},{"kind":"text","text":" "},{"kind":"internalParam","text":"newWindow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nukeui\/videoplayerview\/willmove(towindow:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/nukeui\/videoplayerview\/willmove(towindow:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/willMove(toWindow:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willMove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toWindow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?)"}],"title":"willMove(toWindow:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@NukeUI@objc(cs)VideoPlayerView(im)willMoveToWindow:","modules":[{"name":"NukeUI"}],"navigatorTitle":[{"kind":"identifier","text":"willMoveToWindow:"}]},"hierarchy":{"paths":[["doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI","doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView"]]},"references":{"doc://com.github.kean.nukeui/documentation/NukeUI/VideoPlayerView/willMove(toWindow:)":{"role":"symbol","title":"willMove(toWindow:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willMove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toWindow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView\/willMove(toWindow:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"willMoveToWindow:"}],"url":"\/documentation\/nukeui\/videoplayerview\/willmove(towindow:)"},"doc://com.github.kean.nukeui/documentation/NukeUI":{"role":"collection","title":"NukeUI","abstract":[{"type":"text","text":"Image loading for SwiftUI, UIKit, and AppKit views."}],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI","kind":"symbol","type":"topic","url":"\/documentation\/nukeui"},"doc://com.github.kean.nukeui/documentation/NukeUI/VideoPlayerView":{"role":"symbol","title":"VideoPlayerView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayerView"}],"abstract":[],"identifier":"doc:\/\/com.github.kean.nukeui\/documentation\/NukeUI\/VideoPlayerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"VideoPlayerView"}],"url":"\/documentation\/nukeui\/videoplayerview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"willMoveToWindow:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willMoveToWindow:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"willMoveToWindow:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIWindow","preciseIdentifier":"c:objc(cs)UIWindow"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"newWindow"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1VideoPlayerView~1willMove(toWindow:)\/title","value":"willMoveToWindow:"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1VideoPlayerView~1willMove(toWindow:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willMoveToWindow:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1VideoPlayerView\/title","value":"VideoPlayerView"},{"op":"replace","path":"\/references\/doc:~1~1com.github.kean.nukeui~1documentation~1NukeUI~1VideoPlayerView\/fragments","value":[{"kind":"identifier","text":"VideoPlayerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}